
#ifndef KEEHIVE_TYPES_H
#define KEEHIVE_TYPES_H

#define CKR_KEEHIVE_MEMORY_ERROR       (0 | CKR_VENDOR_DEFINED)
#define CKR_KEEHIVE_SO_INVALID         (1 | CKR_VENDOR_DEFINED)
#define CKR_KEEHIVE_SO_INIT_ERROR      (2 | CKR_VENDOR_DEFINED)
#define CKR_KEEHIVE_SO_ERROR           (3 | CKR_VENDOR_DEFINED)
#define CKR_KEEHIVE_DER_SYNTAX_ERROR   (4 | CKR_VENDOR_DEFINED)
#define CKR_KEEHIVE_DER_RANGE_ERROR    (5 | CKR_VENDOR_DEFINED)
#define CKR_KEEHIVE_DER_UNKNOWN_ERROR  (6 | CKR_VENDOR_DEFINED)

#endif //KEEHIVE_TYPES_H
