#ifndef KEEHIVE_CONSTANTS_H
#define KEEHIVE_CONSTANTS_H

typedef enum {
    KEEHIVE_E_SUCCESS,
    KEEHIVE_E_MEMORY_ERROR,
    KEEHIVE_E_SO_INVALID,
    KEEHIVE_E_SO_INIT_ERROR,
    KEEHIVE_E_SO_ERROR,
    KEEHIVE_E_DER_ERROR,
} KeehiveError;

#endif //KEEHIVE_CONSTANTS_H
